# ADR Registry - 架構決策記錄註冊表
# 由 /adr 指令和 Architecture Advisor 自動維護

metadata:
  version: "1.0"
  last_updated: "2025-01-09"
  total_decisions: 1
  next_number: 2

# ADR 清單 (按編號排序)
decisions:
  - number: "001"
    title: "Project Setup and Development Workflow"
    file: "adr-001-project-setup.md"
    status: "accepted"
    date_created: "2025-01-09"
    date_updated: "2025-01-09"
    category: "process"
    decision_makers: ["AI System", "Project Setup"]
    tags: ["workflow", "development", "initial-setup"]
    supersedes: []
    superseded_by: null
    related_decisions: []

# 分類統計
categories:
  process: 1
  technology_selection: 0
  architecture_pattern: 0
  infrastructure: 0
  security: 0
  performance: 0

# 狀態統計
status_counts:
  proposed: 0
  accepted: 1
  deprecated: 0
  superseded: 0

# 最近活動
recent_activity:
  - action: "created"
    adr_number: "001"
    date: "2025-01-09"
    description: "Initial project setup ADR created"

# ADR 模板映射
templates:
  technology_selection: "templates/technology-selection.md"
  architecture_pattern: "templates/architecture-pattern.md"
  infrastructure_choice: "templates/infrastructure-choice.md"
  process_decision: "templates/process-decision.md"

# 自動化規則
automation:
  auto_detect_triggers:
    - dependency_changes: true
    - config_file_updates: true
    - architecture_discussions: true

  notification_settings:
    slack_webhook: null
    email_notifications: false

  review_schedule:
    frequency: "quarterly"
    next_review: "2025-04-09"